### ISSUE TITLE
Is this package still development ?

### ISSUE THREAD

**Issue by zsz00** [JuliaIO/Formatting.jl#106]

**Comment by ScottPJones** [comment]
I forked this years ago when it wasn't being maintained at all (back in 2015), and it seems to not be maintained again.
You should switch to [Format.jl](https://github.com/JuliaString/Format.jl), which is being actively worked on.

**Comment by zsz00** [comment]
Hope  this information will be in the readme

**Comment by ScottPJones** [comment]
Hard to get the README updated though, since it seems that no PRs are being merged 😞

**Comment by juliohm** [comment]
Can someone please make the deprecation of the package official so that people can decide if they need to migrate to Format.jl? We are currently depending on Formatting.jl and are concerned that there is no active development in 4 years here.

**Comment by carstenbauer** [comment]
Maybe going to far, but perhaps we could even make Format.jl a breaking release of Formatting.jl? (Why did you start a new package to begin with @ScottPJones?)

**Comment by ScottPJones** [comment]
> Maybe going to far, but perhaps we could even make Format.jl a breaking release of Formatting.jl? (Why did you start a new package to begin with @ScottPJones?)

I started it many years ago (back in 2015/2016) when I needed to use it, but it was in a personal repo (before JuliaIO was created), and it was not being maintained, so I couldn't get bug fixes and features that I needed merged in.
Around 5 years ago IIRC it was moved to the JuliaIO org, and some of the bugs were fixed (I backported a few of my fixes from Format.jl to Formatting.jl during that period), but then it lapsed into not being maintained again over the past 3-4 years.

Recently I'd taken to fixing all of the bugs that Format.jl had inherited from Formatting.jl, and making PRs to packages so that they wouldn't be exposed to a number of critical bugs (mostly in the Python format style support), by switching them to Format.jl.
